#!/bin/env python

import json
import os
import sys
from pathlib import Path

import bilby
import matplotlib.pyplot as plt
import numpy as np
import pipeline_argument_parser
from loguru import logger

from pygwb.baseline import Baseline
from pygwb.detector import Interferometer

if __name__ == "__main__":
    args = pipeline_argument_parser.args
    params = pipeline_argument_parser.params
    params.alphas = json.loads(params.alphas_delta_sigma_cut)
    params.interferometer_list = json.loads(params.interferometer_list)
    logger.info(f"Successfully imported parameters from paramfile.")
    outfile_path = Path(args.param_file)
    outfile_path = outfile_path.with_name(
        f"{outfile_path.stem}_final{outfile_path.suffix}"
    )
    params.save_paramfile(str(outfile_path))
    logger.info(f"Saved final param file at {outfile_path}.")

    """
    X TODO X make this into a param in the arg class?
    """
    pipe_calc_point_estimate = True  # if False, it will only compute the CSDs and PSDs, if True, it will compute until the point estimates
    pipe_pickle_baseline = True

    ifo_1 = Interferometer.from_parameters(params.interferometer_list[0], params)
    ifo_2 = Interferometer.from_parameters(params.interferometer_list[1], params)
    logger.info(f"Loaded up interferometers with selected parameters.")

    if params.gate_data:
        logger.info(f"Applying gates.")
        gate_params = { 
                "gate_tzero":params.gate_tzero,
                "gate_tpad":params.gate_tpad,
                "gate_threshold":params.gate_threshold,
                "cluster_window":params.cluster_window,
                "gate_whiten":params.gate_whiten,
                }
        ifo_1.gate_data_apply(**gate_params)
        logger.info(f"Gates for IFO 1:{ifo_1.gates}")
        ifo_2.gate_data_apply(**gate_params)
        logger.info(f"Gates for IFO 2:{ifo_2.gates}")

    base_12 = Baseline.from_parameters(ifo_1, ifo_2, params)
    logger.info(
        f"Baseline with interferometers {ifo_1.name}, {ifo_2.name} initialised."
    )

    logger.info(f"Setting PSDs and CSDs of the baseline...")
    base_12.set_cross_and_power_spectral_density(params.frequency_resolution)
    base_12.set_average_power_spectral_densities()
    base_12.set_average_cross_spectral_density()

    logger.info(f"... done.")

    """
    check nothing's gone wrong in the frequency handling...
    """
    deltaF = base_12.frequencies[1] - base_12.frequencies[0]
    if abs(deltaF - params.frequency_resolution) > 1e-6:
        raise ValueError("Frequency resolution in PSD/CSD is different than requested.")

    base_12.calculate_delta_sigma_cut(
        params.delta_sigma_cut,
        params.alphas,
        flow=params.flow,
        fhigh=params.fhigh,
    )

    logger.info(
        f"times flagged by the delta sigma cut as badGPStimes:{base_12.badGPStimes}"
    )

    if pipe_calc_point_estimate:
        logger.info(f"calculating the point estimate and sigma...")

        base_12.set_point_estimate_sigma(
            alpha=params.alpha,
            fref=params.fref,
            flow=params.flow,
            fhigh=params.fhigh,
            badtimes=np.array([]),  # use this line to override the delta sigma cut
        )

        logger.success(
            f"Ran stochastic search over times {int(params.t0)}-{int(params.tf)}"
        )
        logger.success(f"\tPOINT ESIMATE: {base_12.point_estimate:e}")
        logger.success(f"\tSIGMA: {base_12.sigma:e}")

        data_file_name = f"point_estimate_sigma_{int(params.t0)}-{int(params.tf)}"

        logger.info(
            "Saving point_estimate and sigma spectrograms, spectra, and final values to file."
        )
        logger.info("Saving average psds and csd to file.")
        base_12.save_point_estimate_spectra(
            params.save_data_type,
            data_file_name,
        )
        base_12.save_psds_csds(
            params.save_data_type,
            data_file_name,
        )
        if pipe_pickle_baseline:
            logger.info("Pickling the baseline.")
            pickle_name = f"{base_12.name}_{int(params.t0)}-{int(params.tf)}.pickle"
            base_12.save_to_pickle(pickle_name)

    else:
        logger.info("Saving average psds and csd to file.")

        data_file_name = f"psds_csds_{int(params.t0)}-{int(params.tf)}"

        base_12.npz_save_psds_csds(
            data_file_name,
            base_12.frequencies,
            base_12.csd,
            base_12.interferometer_1.average_psd,
            base_12.interferometer_2.average_psd,
        )
