name: Docs
on: [push, pull_request, workflow_dispatch]
permissions:
    contents: write
jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          pip install --upgrade pip setuptools
          pip install ipykernel ipython==8.12.0 jupyter
          pip install sphinx numpydoc nbsphinx sphinx_rtd_theme sphinx-tabs autodoc ipython-genutils
          pip install .
      - name: Sphinx build
        run: |
    	  cd docs
    	  cp ../tutorials/*.ipynb ./
    	  cp ../tutorials/*.dat ./
    	  cp -r ../tutorials/input ./
    	  rm integrationTest*.ipynb
          sphinx-build docs docs/_build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/_build/
          force_orphan: true
